[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
rational-dex-program = "3rFzgYuL3EBragfJhc9ELMUQPeLvP4qApJyWpTBMuZ7g"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
